name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Install Sonar Scanner
      run: npm install -g sonarqube-scanner

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=zomato
          -Dsonar.projectName=zomato

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
        tar zxvf trivy_0.18.3_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/

    - name: Trivy File Scan
      run: trivy fs .

    - name: Build Docker Image
      run: docker build -t image1 .

    - name: Tag Docker Image
      run: docker tag image1 siddu009/mydockerprojectfor5pm:myzomatoimage

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push siddu009/mydockerprojectfor5pm:myzomatoimage

    - name: Trivy Image Scan
      run: trivy image siddu009/mydockerprojectfor5pm:myzomatoimageSTEP-8: Push Code to GitHub
